# Generated by Django 5.0.6 on 2024-06-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('foto_pro', models.ImageField(upload_to='productos')),
                ('precio', models.CharField(max_length=9)),
                ('nombre_pro', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CarroCompra',
            fields=[
                ('nro_carro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rut_cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('nro_pedido', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente')], max_length=10)),
                ('rut_cli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.cliente')),
            ],
        ),
    ]
