# Generated by Django 5.0.6 on 2024-06-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_c',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='rut_cli',
            new_name='rut',
        ),
    ]
