# Generated by Django 5.0.6 on 2024-06-30 02:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_nombre_c_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrocompra',
            name='nro_carro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.CreateModel(
            name='ProductoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)])),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.producto')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='carrocompra',
            name='productos',
            field=models.ManyToManyField(to='aplicacion.productocarro'),
        ),
    ]
