# Generated by Django 5.0.6 on 2024-06-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_nombre_c_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente')], max_length=10),
        ),
    ]
