# Generated by Django 5.0.6 on 2024-06-29 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
