# Generated by Django 5.0.6 on 2024-06-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado')], default='Pendiente', max_length=10),
        ),
    ]
