# Generated by Django 5.0.6 on 2024-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_pedidos_estado_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocarro',
            old_name='codigo_producto',
            new_name='codigo',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado')], default='Pendiente', max_length=10),
        ),
    ]
