# Generated by Django 5.0.6 on 2024-06-30 21:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_rename_codigo_producto_productocarro_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrocompra',
            old_name='nro_carro',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='carrocompra',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrocompra',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='carrocompra',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
