# Generated by Django 5.0.6 on 2024-07-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
