# Generated by Django 5.0.6 on 2024-07-01 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocarro',
            old_name='cantidad_producto',
            new_name='cantidad',
        ),
        migrations.RemoveField(
            model_name='productocarro',
            name='email',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('nro_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('estado_pedido', models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente')], default='Pendiente', max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplicacion.cliente')),
                ('productos', models.ManyToManyField(to='aplicacion.productocarro')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
