# Generated by Django 5.0.6 on 2024-07-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_rename_cantidad_producto_productocarro_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productocarro',
            old_name='codigo',
            new_name='codigo_producto',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='productocarro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
