# Generated by Django 5.0.6 on 2024-07-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0021_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado')], default='Pendiente', max_length=10),
        ),
    ]
