# Generated by Django 5.0.6 on 2024-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0023_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocarro',
            name='codigo_carro',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente')], default='Pendiente', max_length=10),
        ),
    ]
