# Generated by Django 5.0.6 on 2024-07-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0026_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagen',
        ),
    ]
