# Generated by Django 5.0.6 on 2024-07-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0029_alter_pedido_estado_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='productocarro',
            name='codigo_pedido',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aplicacion.pedido'),
            preserve_default=False,
        ),
    ]
