# Generated by Django 5.0.6 on 2024-07-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0030_remove_pedido_productos_productocarro_codigo_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='productocarro',
            name='codigo_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='aplicacion.pedido'),
        ),
        migrations.AlterField(
            model_name='productocarro',
            name='codigo_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto', to='aplicacion.producto'),
        ),
    ]
