# Generated by Django 5.0.6 on 2024-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0031_alter_pedido_estado_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_pedido',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
