# Generated by Django 5.0.6 on 2024-07-06 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0032_pedido_direccion_pedido_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_pedido',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
