# Generated by Django 5.0.6 on 2024-07-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0033_pedido_total_pedido_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_pedido',
            field=models.CharField(choices=[('SONIDO', 'Sonido'), ('REFRIGERACION', 'Refrigeración (Ventiladores/Líquida)'), ('ALMACENAMIENTO', 'Almacenamiento (HDD/SSD)'), ('RATONES', 'Ratones'), ('MONITORES', 'Monitores'), ('TARJETAS_GRAFICAS', 'Tarjetas Gráficas'), ('ACCESORIOS', 'Accesorios'), ('FUENTES_DE_ALIMENTACION', 'Fuentes de Alimentación'), ('PLACAS_BASE', 'Placas Base'), ('MEMORIA_RAM', 'Memoria RAM'), ('GABINETES', 'Gabinetes'), ('TECLADOS', 'Teclados'), ('PROCESADORES', 'Procesadores')], default='CATEGORIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10),
        ),
    ]
