# Generated by Django 5.0.6 on 2024-07-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0034_producto_estado_pedido_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_pedido',
            field=models.CharField(choices=[('TECLADOS', 'Teclados'), ('GABINETES', 'Gabinetes'), ('FUENTES_DE_ALIMENTACION', 'Fuentes de Alimentación'), ('TARJETAS_GRAFICAS', 'Tarjetas Gráficas'), ('ACCESORIOS', 'Accesorios'), ('RATONES', 'Ratones'), ('SONIDO', 'Sonido'), ('MONITORES', 'Monitores'), ('MEMORIA_RAM', 'Memoria RAM'), ('PLACAS_BASE', 'Placas Base'), ('VENTILACION', 'Ventilación (Ventiladores/Líquida)'), ('ALMACENAMIENTO', 'Almacenamiento (HDD/SSD)'), ('PROCESADORES', 'Procesadores')], default='CATEGORIA', max_length=25),
        ),
    ]
