# Generated by Django 5.0.6 on 2024-07-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0035_alter_pedido_estado_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado_pedido',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('VENTILACION', 'Ventilación (Ventiladores/Líquida)'), ('RATONES', 'Ratones'), ('ALMACENAMIENTO', 'Almacenamiento (HDD/SSD)'), ('ACCESORIOS', 'Accesorios'), ('PLACAS_BASE', 'Placas Base'), ('MEMORIA_RAM', 'Memoria RAM'), ('FUENTES_DE_ALIMENTACION', 'Fuentes de Alimentación'), ('TECLADOS', 'Teclados'), ('GABINETES', 'Gabinetes'), ('SONIDO', 'Sonido'), ('PROCESADORES', 'Procesadores'), ('TARJETAS_GRAFICAS', 'Tarjetas Gráficas'), ('MONITORES', 'Monitores')], default='CATEGORIA', max_length=25),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=10),
        ),
    ]
