# Generated by Django 5.0.6 on 2024-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0036_remove_producto_estado_pedido_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ALMACENAMIENTO', 'Almacenamiento (HDD/SSD)'), ('GABINETES', 'Gabinetes'), ('TARJETAS_GRAFICAS', 'Tarjetas Gráficas'), ('VENTILACION', 'Ventilación (Ventiladores/Líquida)'), ('TECLADOS', 'Teclados'), ('ACCESORIOS', 'Accesorios'), ('PROCESADORES', 'Procesadores'), ('RATONES', 'Ratones'), ('SONIDO', 'Sonido'), ('MEMORIA_RAM', 'Memoria RAM'), ('PLACAS_BASE', 'Placas Base'), ('MONITORES', 'Monitores'), ('FUENTES_DE_ALIMENTACION', 'Fuentes de Alimentación')], default='PROCESADORES', max_length=25),
        ),
    ]
