# Generated by Django 5.0.6 on 2024-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0037_alter_pedido_estado_pedido_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('TECLADOS', 'Teclados'), ('ACCESORIOS', 'Accesorios'), ('SONIDO', 'Sonido'), ('MONITORES', 'Monitores'), ('PROCESADORES', 'Procesadores'), ('GABINETES', 'Gabinetes'), ('TARJETAS_GRAFICAS', 'Tarjetas Gráficas'), ('ALMACENAMIENTO', 'Almacenamiento (HDD/SSD)'), ('RATONES', 'Ratones'), ('MEMORIA_RAM', 'Memoria RAM'), ('FUENTES_DE_ALIMENTACION', 'Fuentes de Alimentación'), ('PLACAS_BASE', 'Placas Base'), ('VENTILACION', 'Ventilación (Ventiladores/Líquida)')], default='PROCESADORES', max_length=25),
        ),
    ]
